version: '3.3'

services:
  proxy:
    image: jwilder/nginx-proxy:latest
    container_name: proxy
    restart: always
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  dns:
    image: andyshinn/dnsmasq
    container_name: dns
    restart: always
    ports:
      - '53535:53/tcp'
      - '53535:53/udp'
    command: '--address=/local/127.0.0.1'
    cap_add:
      - NET_ADMIN

  webserver:
    image: nginx:latest
    container_name: webserver
    volumes:
      - .:/app
      - ./data/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wp
    environment:
      VIRTUAL_HOST: testing.localhost

  db:
    image: mysql:5.7
    container_name: wp_db
    volumes:
      - ./data/db:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wp_database
      MYSQL_USER: wp_dbu
      MYSQL_PASSWORD: please_change_me!1!

  wp:
    build:
      context: data/docker
      dockerfile: Dockerfile
    image: wp:latest
    container_name: wp
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      WP_TITLE: 'New WP Title'
      WP_HOME: http://testing.localhost
