version: '3.3'

services:
  webserver:
    image: nginx:latest
    container_name: webserver
    # ports:
    #   - '8080:80'
    volumes:
      - .:/app
      - ./data/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wp
    environment:
      VIRTUAL_HOST: testing.localhost
    networks:
      - proxy_dev_network
      - wp_network

  db:
    image: mysql:5.7
    container_name: wp_db
    volumes:
      - ./data/db:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wp_database
      MYSQL_USER: wp_dbu
      MYSQL_PASSWORD: please_change_me!1!
    networks:
      - wp_network

  wp:
    build:
      context: data/docker
      dockerfile: Dockerfile
    image: wp:latest
    container_name: wp
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      WP_TITLE: 'New WP Title'
      WP_HOME: http://testing.localhost
    networks:
      - wp_network
      - proxy_dev_network

networks:
  proxy_dev_network:
    external: true
  wp_network: