version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - .:/app
      - ./data/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wp

  db:
    image: mysql:5.7
    container_name: wp_db
    volumes:
      - ./data/db:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wp_database
      MYSQL_USER: wp_dbu
      MYSQL_PASSWORD: please_change_me!1!

  wp:
    build:
      context: data/docker
      dockerfile: Dockerfile
    image: wp:latest
    container_name: wp
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      WP_TITLE: 'New WP Title'
